---
title: "Avengers"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

```{r}
library(tidyverse)
av <- read.csv("https://raw.githubusercontent.com/fivethirtyeight/data/master/avengers/avengers.csv", stringsAsFactors = FALSE)
view(av)
```

```{r}
names(av)
av0 = av %>% filter(Name.Alias != "")
av1 = av0 %>% gather(key = time, value = death, c(11, 13, 15, 17, 19)) %>% 
  select(Name.Alias, time, death) %>%
  mutate(time = parse_number(time))
av2 = av0 %>% gather(key = time, value = return, c(12, 14, 16, 18, 20)) %>% 
  select(Name.Alias, time, return) %>%
  mutate(time = parse_number(time))
av.neat = left_join(av1, av2, by = c("Name.Alias", "time"))
av0 = av0 %>% filter(Name.Alias != "Vance Astrovik")
av1 = av0 %>% gather(key = time, value = death, c(11, 13, 15, 17, 19)) %>% 
  select(Name.Alias, time, death) %>%
  mutate(time = parse_number(time))
av2 = av0 %>% gather(key = time, value = return, c(12, 14, 16, 18, 20)) %>% 
  select(Name.Alias, time, return) %>%
  mutate(time = parse_number(time))
av.neat = left_join(av1, av2, by = c("Name.Alias", "time"))


av.neat$death = replace(av.neat$death, av.neat$death == "", NA)
av.neat$return = replace(av.neat$return, av.neat$return == "", NA)
```

